### ISSUE TITLE
Some albumart not loading

### ISSUE THREAD

**Issue by niekez** [dough10/PolySonic#31]
For some albums, albumart is not loading. If I look on the web, albumart is there for the albums. If I redownload the albumart, it still won't load. Even after I empty the cache. It seems random.

Screenshots:

![screenshot from 2015-05-31 13-26-02](https://cloud.githubusercontent.com/assets/6378007/7901754/0e5ed07c-0799-11e5-9497-efc2e767b6d4.png)

![screenshot from 2015-05-31 13-29-57](https://cloud.githubusercontent.com/assets/6378007/7901761/30a36512-0799-11e5-95ab-9b1894bc68ac.png)

**Comment by dough10** [comment]
i think this has something to do with the app using ID3 sort method and the web interface using the subsonic traditional sort method. i have noticed in the version i am working on now that the art doesn't always match between the two modes. when i am able to get 0.2.4 stable it will have a option to change between the two sort methods and that should correct this issue as well as enabling ratings. for now you could try to rescan library in the subsonic web interface then clear cache in polysonic and see if that corrects any of them. thank you for bringing this to my attention.

**Comment by dough10** [comment]
i had said in the last post that i would put in a switch to go from ID3 to traditional subsonic sorting methods but it doesn't looks like that is going to happen in 0.2.4 as i had planed. it causes to many issues i have not been able to solve at the moment for that to happen. this issue isn't actually a app issue but rather a issue with the subsonic api its self. i reported this on the official subsonic api forum and Sindre said he will look into it. i hope it is sorted in api version 1.13.0 (what ever turns out to be the next subsonic version)

**Comment by niekez** [comment]
Yeah I thought as I noticed the same problem with dsub. Thanks for looking
into it!

Op do 2 jul. 2015 om 02:32 schreef jimi doughten <notifications@github.com>:
