### ISSUE TITLE
Bitrate popup cut off and unscrollable

### ISSUE THREAD

**Issue by paour** [dough10/PolySonic#32]
osx 10.10.4, Chrome 43.0.2357.130 (64-bit)

![polysonic](https://cloud.githubusercontent.com/assets/90963/8498811/b40e4d98-218b-11e5-8b4b-1ec909c65dbb.png)

**Comment by dough10** [comment]
thank you for bring this to my attention. on windows and chromeOS the dropdown is the same size but has a scroll bar (i do not have a mac @ this time for testing).  in 0.2.4 this should be fixed. i have made a few css changes to the dropdowns because they haven't looked how i thought they should. the update is close to completion i am just testing for obvious bugs before i push it. i will push it in a day or so if i don't find any bugs i feel need to be addressed immediately.  the current working branch is 0.2.4v2 if you would like to clone and see if i have the issue resolved.

**Comment by dough10** [comment]
0.2.4 has been released and should be updated on clients today. if this is not fixed in 0.2.4 please let me know and i will see what i can do to get it fixed asap.

**Comment by paour** [comment]
Confirmed fixed, thank you!
