### ISSUE TITLE
login and url issues

### ISSUE THREAD

**Issue by dough10** [dough10/PolySonic#37]
Anyone having issues with connecting to their Subsonic with Polysonic? My last few reviews on web store have not been so good. Anyone tried to connect to a Subsonic server with a api version higher then 1.12.0?
![screenshot 2015-07-21 at 8 46 20 am](https://cloud.githubusercontent.com/assets/7014926/8802807/45c708fa-2f89-11e5-8b5a-51931bbe0dcb.png)
![screenshot 2015-07-21 at 8 46 31 am](https://cloud.githubusercontent.com/assets/7014926/8802811/49ff0008-2f89-11e5-9258-2c05c998af1a.png)

**Comment by acroyear** [comment]
Ok, I just left feedback on connectivity at the forum. At my office polysonic was fine, but here at home, I couldn't connect to whatever my server was configured to be. In my case it was specifically saying "Can't connect". At this point, the loading spinner stayed loading and there was no way out of it. My only recourse to clearing the memory was to uninstall and reinstall.

My feedback is that the best option to handle such a situation is to just pop up the config editor screen again so the user can verify the settings. SubFire will timeout and close the loading dialog, allowing the user to reconfigure. (yes, I'm aware that isn't easy to test - consider doing it by what I suggest: temporarily change your server's port or host, then see how polysonic reacts and fix it, then change it back and see that polysonic allows you to change it back as well rather than just hanging).

**Comment by dough10** [comment]
Just to get a idea where to find this in code. You were loading  a client that had settings already saved in synced settings? Meaning you didn't set up the client it had settings pulled from another install.

**Comment by acroyear** [comment]
Does Polysonic sync settings through Chrome? SubFire doesn't (since I have so many other platforms to support). In any case, because I couldn't get to the settings dialog, I couldn't see what my settings actually were to infer how they'd come in.  Both boxes have had Polysonic on them since the early releases so both of them originally had their logins saved independently.

**Comment by dough10** [comment]
Ahh I see.  But yes polysonic does sync setting between client installs as long as you are using the same google account for both pc's.  At least it is supposed to. come to think of it it might not sync bitrate. I will have to look into that.

**Comment by acroyear** [comment]
I personally can't have syncing bitrates. My work connection is *horrid* and will disconnect on the variable-rate mp3s from Amazon if my client is sending 'unlimited' (meaning stream the original source file). At home, close to the server, then unlimited is just fine.

That said, do what works for your primary customers, of course, and having only Chrome customers makes such account info sync ideal. SubFire's still my primary choice for obvious reasons. :)

**Comment by dough10** [comment]
Yeah it even syncs bitrate. But I will change that i think. I hadn't noticed cause I am in and out of clients to much. 3 versions (source, build and production) installed on 2 pc's all with diff settings. My home internet is poor so when streaming outside the house I turn down the bitrate and I don't wanna have to change it back every time when I get home. 

I think it would be best if I save the bitrate as a local client setting. But I will wait till 0.2.7 for that.
