### ISSUE TITLE
No https support

### ISSUE THREAD

**Issue by openaspace** [dough10/PolySonic#45]
Hello, 
very nice app but the https support was necessary I think! :)

**Comment by dough10** [comment]
I do not have https setup on my box so i haven't been able to test ssl. but with that  said I haven't done anything that would stop https from working. In theory as long as the server credentials are configured correctly it should work. I will see about setting up ssl on my box and post back when i find something out.

**Comment by dough10** [comment]
Is the cert self signed?

**Comment by openaspace** [comment]
Yes is the default subsonic cert.

Inviato da iPad

**Comment by dough10** [comment]
I think what is happening is the xmlHttpRequest is rejected due to the self signed cert. (I have not been able to find anyway to force the request to accept a self signed cert) 

You could add the cert as a trusted authority on your machine. That should allow you to connect with PolySonic to your server over https.

The following steps are for adding a cert as a trusted authority on Chrome OS. The steps will be close to the same on any other system. I can update with windows instruction when i get around my windows machine

1. navigate to the Subsonic server in chrome.

2. Click the https lock in the address bar.  
![screenshot 2015-10-02 at 12 37 51 pm](https://cloud.githubusercontent.com/assets/7014926/10253484/478c0844-6903-11e5-952f-859432b71f05.png)

3. Click the connection tab in the dropdown. 
Then click the certificate information link
![screenshot 2015-10-02 at 12 16 55 pm](https://cloud.githubusercontent.com/assets/7014926/10253527/824c0fc4-6903-11e5-85c5-6a41fc4c1dbb.png)

4. Click the details tab of the dialog that is opened. Then click the export button
![screenshot 2015-10-02 at 12 17 33 pm](https://cloud.githubusercontent.com/assets/7014926/10253602/e26cb0c0-6903-11e5-982a-4f5351e16040.png)

5. Save the cert somewhere you will be able to find it. (desktop for example)
Save it as a PKCS #7 single cert.
![screenshot 2015-10-02 at 12 19 16 pm](https://cloud.githubusercontent.com/assets/7014926/10253680/455eb462-6904-11e5-8502-4d54c64f010d.png)

6. Open Chrome settings menu and open advanced settings at bottom of the page. Look for HTTPS / SSL and open that dialog.
![screenshot 2015-10-02 at 12 18 17 pm](https://cloud.githubusercontent.com/assets/7014926/10253741/a863872c-6904-11e5-81bc-8dd41a802b2f.png)

7. In the certificate manager click on the authorities tab and click the import button.
![screenshot 2015-10-02 at 12 18 45 pm](https://cloud.githubusercontent.com/assets/7014926/10253855/82475d24-6905-11e5-9646-19926f7ffe37.png)

8. Navigate to where you saved the file. Change the import type to PKCS #7 single cert. Select the file and Ok though. 

9. Refresh the page and the lock icon should look like the image below. 
![screenshot 2015-10-02 at 12 16 18 pm](https://cloud.githubusercontent.com/assets/7014926/10253915/e6490e9e-6905-11e5-9c44-bbdaab8b0fe2.png)

If all went well you should now be able to connect PolySonic  to your Subsonic server with the ssl address.

If this works please let me know.

**Comment by dough10** [comment]
I have not been able to get SSL working on my Subsonic box (FreeNAS plugin jail, Subsonic version 5.2.1, FreeNAS version 9.3-STABLE) I will try to install on a virtual box and see if i can get ssl working there.

**Comment by dough10** [comment]
I have tested and PolySonic can connect to Subsonic over https using a valid cert or if using default cert it must be imported as a trusted authority using a method like my previous post.
